# Generated by Django 4.1 on 2022-09-10 12:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/alessandracosta8/image/upload/v1662812379/default_profile_picture_id2iuq.png', max_length=255, verbose_name='picture'),
        ),
    ]
